wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
architecture:
  desc: null
  value: '-'
dataset:
  desc: null
  value: DeepFake Detection Challenge
epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1714473214.0
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.6
      8:
      - 1
      - 2
      - 4
      - 5
      13: darwin-arm64
